apiVersion: v1
kind: ReplicationController
metadata:
  name: luckwine-oss-service
  namespace: prod
spec:
  replicas: 1
  selector:
    app: luckwine-oss-service
  template:
    metadata:
      labels:
        app: luckwine-oss-service
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "www.abc.com"
      containers:
        - name: luckwine-oss-service
          image: luckwine-oss-service:latest
          imagePullPolicy: IfNotPresent
#          securityContext:
#            readOnlyRootFilesystem: true
#            runAsNonRoot: true
          ports:
            - containerPort: 8030
          env:
            - name: JAVA_OPTIONS
              value: -Duser.timezone=GMT+8 -Xms128m -Xmx256m -Dspring.profiles.active=prod
          volumeMounts:
            - name: luckwine-volume
              mountPath: /data/applog
      volumes:
        - name: luckwine-volume
          hostPath:
            path: /data/docker/luckwine-oss-service